name = "nautilus-log-auth"
main = "src/worker.mjs"
compatibility_date = "2026-08-30"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://roamresearch.com"
GOOGLE_OAUTH_REDIRECT_URI = "https://nautilus-log-auth-preview.kidsseeghosts.workers.dev/oauth/callback"
OAUTH_ISSUER = "production"

[[d1_databases]]
binding = "NAUTILUS_AUTH_DB"
database_name = "nautilus-log-auth"
database_id = "ec2188ba-016e-4b37-a1a0-25d710e6d6c0"
migrations_dir = "migrations"

[env.preview]
name = "nautilus-log-auth-preview"
workers_dev = true

[env.preview.vars]
ALLOWED_ORIGINS = "https://roamresearch.com"
GOOGLE_OAUTH_REDIRECT_URI = "https://nautilus-log-auth-preview.kidsseeghosts.workers.dev/oauth/callback"
OAUTH_ISSUER = ""
OAUTH_CALLBACK_FORWARD_URL = "https://nautilus-log-auth.kidsseeghosts.workers.dev/oauth/callback"

[[env.preview.d1_databases]]
binding = "NAUTILUS_AUTH_DB"
database_name = "nautilus-log-auth-preview"
database_id = "83fc48dc-7fc7-4078-a7c2-e790ba9553fc"
migrations_dir = "migrations"
